services:
  holiday-app:
    build: .
    container_name: holiday-app
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: holiday-redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: holiday-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

volumes:
  redis-data: